### ISSUE TITLE
Add ability to check status of HF. If its installed, don't install it again.

### ISSUE THREAD

**Issue by kaushalmall** [kaushalmall/aem-hotfix-installer#2]

**Comment by schoudry** [comment]
this might help - http://experience-aem.blogspot.com/2015/12/aem-61-this-and-that.html#AEM_61_CHECK_HOTFIXES_FEATURE_PACKS

**Comment by kaushalmall** [comment]
Closed with https://github.com/kaushalmall/aem-hotfix-installer/pull/15
