### ISSUE TITLE
Add check flag

### ISSUE THREAD

**Issue by davidjgonzalez** [kaushalmall/aem-hotfix-installer#5]
Run with a check flag to see what The delta in installed HFs vs what is in config.properties

**Comment by kaushalmall** [comment]
@davidjgonzalez I added the check flag. 

https://github.com/kaushalmall/aem-hotfix-installer/commit/933a74ce79550773126d7ec085efb9c085189ceb

and PR https://github.com/kaushalmall/aem-hotfix-installer/pull/10. Let me know if this looks good. Added the check flag command in README as well.
