### ISSUE TITLE
can't disable the yes or no prompt

### ISSUE THREAD

**Issue by ynakagawa** [kaushalmall/aem-hotfix-installer#6]
in order to write a script to use this, i would need the user prompts disable.  there should be a flag for a silent mode operation.

**Comment by kaushalmall** [comment]
@ynakagawa the default was silent mode, but I ran into an issue where it tried installing the next HF in the sequence while AEM was still processing the HF before that. The second HF install call would then return a 500! 

I need to figure out how to get status of the current HF install process before moving to the next one. Once I figure out how to do that, then I can remove the Y/N prompt all together.

**Comment by kaushalmall** [comment]
@ynakagawa I added the silent flag support. Also updated README. Please let me know if it works and close the issue accordingly.
